services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:10.4.1
    volumes:
      - ./mounted/ipc:/ipc
      - ./mounted/db:/data/db
      - ./environments:/data/environments
    environment:
      - NETWORK=preprod
    ports:
      - "3001:3001"
    # command:
    #   [
    #     "run",
    #     "--config",
    #     "/data/environments/config.json",
    #     "--database-path",
    #     "/data/db",
    #     "--socket-path",
    #     "/ipc/node.socket",
    #     "--host-addr",
    #     "127.0.0.1",
    #     "--port",
    #     "3001",
    #     "--topology",
    #     "/data/environments/topology.json",
    #   ]
