# Use root/example as user/password credentials
version: "3.1"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      REDIS_USERNAME: default
      REDIS_PASSWORD: defaultPassword
